@startuml
!include ../_theme.puml
title Author Content
top to bottom direction

rectangle "Capability Module Definition" as Define <<zoom>> [[define_capability_module/_mod_.puml]]
rectangle "Authoring Artifact Build" as Build <<zoom>> [[build_authoring_artifact/_mod_.puml]]

Define --> Build : supplies source graph to
@enduml
