@startuml
!include _theme.puml
title Vapor Happens
top to bottom direction

rectangle "Author Content" as Author <<zoom>> [[author_content/_mod_.puml]]
rectangle "Distribute Content" as Distribute <<zoom>> [[distribute_content/_mod_.puml]]
rectangle "Packagepack Launch" as Launch <<zoom>> [[launch_packagepack/_mod_.puml]]
rectangle "Locked Runtime Execution" as Run <<zoom>> [[run_locked_runtime/_mod_.puml]]

Author --> Distribute : produces artifacts for
Distribute --> Launch : installs content for
Launch --> Run : prepares lock for
@enduml
