@startuml
!include _theme.puml
title Author Content
top to bottom direction

rectangle "Capability Module Definition" as Define <<zoom>> [[author_content/define_capability_module.puml]]
rectangle "Authoring Artifact Build" as Build <<zoom>> [[author_content/build_authoring_artifact.puml]]

Define --> Build : supplies source graph to
@enduml
