@startuml
!include _theme.puml
title Distribute Content
top to bottom direction

rectangle "Workshop Item Publication" as Publish <<zoom>> [[distribute_content/publish_workshop_item.puml]]
rectangle "Workshop Item Installation" as Install <<zoom>> [[distribute_content/install_workshop_item.puml]]

Publish --> Install : makes Workshop item available to
@enduml
